### ISSUE TITLE
Some tests fail on i686, ppc64le, aarch64

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/backtrace-rs#204]
### i686

```rust
---- smoke_test_frames stdout ----
symbol  ip:0x565814b6 address:0x56581450 name:backtrace::backtrace::libunwind::trace::ha9ef84cdc10829cb file:/builddir/build/BUILD/backtrace-0.3.30/src/backtrace/libunwind.rs lineno:88 
symbol  ip:0x565814b6 address:0x56581450 name:backtrace::backtrace::trace_unsynchronized::hd3c9aaaaa7d9af15 file:/builddir/build/BUILD/backtrace-0.3.30/src/backtrace/mod.rs lineno:66 
symbol  ip:0x565814b6 address:0x56581450 name:backtrace::backtrace::trace::h607db5f519792120 file:/builddir/build/BUILD/backtrace-0.3.30/src/backtrace/mod.rs lineno:53 
symbol  ip:0x565814b6 address:0x56581450 name:smoke::smoke_test_frames::frame_4::hf19f297543340700 file:tests/smoke.rs lineno:30 
symbol  ip:0x565803dc address:0x565803c0 name:smoke::smoke_test_frames::h47fdd59b75a54d6d file:tests/smoke.rs lineno:24 
symbol  ip:0x565803dc address:0x565803c0 name:smoke::smoke_test_frames::{{closure}}::ha7844e1896277211 file:tests/smoke.rs lineno:23 
symbol  ip:0x565803dc address:0x565803c0 name:core::ops::function::FnOnce::call_once::h956a8c8cb80257b4 file:/builddir/build/BUILD/rustc-1.35.0-src/src/libcore/ops/function.rs lineno:231 
thread 'smoke_test_frames' panicked at '0x565803c0 < 0x56581440 (frame_3 tests/smoke.rs:27)', tests/smoke.rs:123:9
```

### ppc64le

```rust
---- backtrace_new_unresolved_should_start_with_call_site_trace stdout ----
stack backtrace:
   0: backtrace::backtrace::libunwind::trace::hbaa3d78b723e53ae (0x116d6fd40)
             at src/backtrace/libunwind.rs:88
      backtrace::backtrace::trace_unsynchronized::h34f3e4e9d2d80a50
             at src/backtrace/mod.rs:66
      backtrace::backtrace::trace::h97213509f2779f09
             at src/backtrace/mod.rs:53
      backtrace::capture::Backtrace::create::h2cd8e8f9e0274517
             at src/capture.rs:163
   1: skip_inner_frames::backtrace_new_unresolved_should_start_with_call_site_trace::h28c5264e6324a2f5 (0x116d1f48c)
             at tests/skip_inner_frames.rs:24
   2: test::__rust_begin_short_backtrace::hb7c024f39e700a27 (0x116d2b9e4)
   3: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h0f2e9c62f884a3aa (0x116d49238)
   4: __rust_maybe_catch_panic (0x116da0524)
   5: std::sys_common::backtrace::__rust_begin_short_backtrace::h266c47ee632bea5f (0x116d4e94c)
   6: std::panicking::try::do_call::hb82c8dd27a217537 (0x116d4640c)
   7: __rust_maybe_catch_panic (0x116da0524)
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}::hfe4983e36f58029f (0x116d4f8e4)
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h8a8c541c59935521 (0x116d98ad8)
  10: std::sys_common::thread::start_thread::hcdfcf23e0e218ee3 (0x116d9d6e0)
  11: std::sys::unix::thread::Thread::new::thread_start::h2d27247835af59ea (0x116d8b418)
  12: start_thread (0x7fff990599a8)
  13: clone (0x7fff991d1d18)
this_ip: 0x116d1f460
thread 'backtrace_new_unresolved_should_start_with_call_site_trace' panicked at 'assertion failed: `(left == right)`
  left: `4677825632`,
 right: `4678155248`', tests/skip_inner_frames.rs:33:5
```

### aarch64

```rust
---- backtrace_new_unresolved_should_start_with_call_site_trace stdout ----
stack backtrace:
   0: backtrace::backtrace::libunwind::trace::hc5255d8b4411a4c1 (0xaaaacbc00f7c)
             at src/backtrace/libunwind.rs:88
      backtrace::backtrace::trace_unsynchronized::h82ea242029c24b86
             at src/backtrace/mod.rs:66
      backtrace::backtrace::trace::h717b20805dc534f5
             at src/backtrace/mod.rs:53
      backtrace::capture::Backtrace::create::h40a482c792f614a6
             at src/capture.rs:163
   1: skip_inner_frames::backtrace_new_unresolved_should_start_with_call_site_trace::hf8076b3b53e6e2fd (0xaaaacbbd0690)
             at tests/skip_inner_frames.rs:24
   2: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1a25535ac5e80ed0 (0xaaaacbbdc0f0)
   3: __rust_maybe_catch_panic (0xaaaacbc211e8)
   4: test::run_test::run_test_inner::{{closure}}::hd1568898ad2ee400 (0xaaaacbbee674)
   5: std::sys_common::backtrace::__rust_begin_short_backtrace::h07c8239a197cb9c0 (0xaaaacbbd0c9c)
   6: std::panicking::try::do_call::h1417884234b1bbb5 (0xaaaacbbd59c8)
   7: __rust_maybe_catch_panic (0xaaaacbc211e8)
   8: std::thread::Builder::spawn_unchecked::{{closure}}::hbc221a2bd68067db (0xaaaacbbd5860)
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha4ad16d9bb8b0b7d (0xaaaacbc136d8)
  10: std::sys::unix::thread::Thread::new::thread_start::h57072ceb8042c9e1 (0xaaaacbc20984)
  11: start_thread (0xffff9c83289c)
  12: thread_start (0xffff9c93220c)
  13: <unknown> (0x0)
this_ip: 0xaaaacbbd067c
thread 'backtrace_new_unresolved_should_start_with_call_site_trace' panicked at 'assertion failed: `(left == right)`
  left: `187650539325052`,
 right: `187650539523668`', tests/skip_inner_frames.rs:33:5
```

**Comment by alexcrichton** [comment]
Thanks for the report but I'm not going to track in this repository issues on other architectures. These are all tested in this repository so local testing may need to be configured differently.
