### ISSUE TITLE
Windows inline frames not reported correctly

### ISSUE THREAD

**Issue by lzybkr** [rust-lang/backtrace-rs#255]
The calls to `SymFromInlineContextW` always pass `0` for the `InlineContext` parameter. This results in duplicated symbols in the backtrace, for example:

```
  13: core::ptr::real_drop_in_place
             at /rustc/.../src/libcore/ptr/mod.rs:175
  14: core::ptr::real_drop_in_place
             at /rustc/.../src/libcore/ptr/mod.rs:175
  15: core::ptr::real_drop_in_place
             at /rustc/.../src/libcore/ptr/mod.rs:175
```

You apparently need to call `SymQueryInlineTrace` and iterate through the inline frames as described in this [StackOverflow answer](https://stackoverflow.com/questions/22487887/why-doesnt-stack-walking-work-properly-when-using-setunhandledexceptionfilter/49950234#49950234)

**Comment by alexcrichton** [comment]
Thanks for the report! Do you have some example code which is generating this trace? Or is there a way I can reproduce it locally?

**Comment by lzybkr** [comment]
I don't, but maybe this sample is the same issue, note frames 6 and 7 have the same name.

```
> type .\src\main.rs
fn main() {
    panic!();
}
> cargo run --release
    Finished release [optimized] target(s) in 0.03s
     Running `target\release\t.exe`                                                                                                                                        thread 'main' panicked at 'explicit panic', src\main.rs:2:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\panicking.rs:477
   6: std::panicking::begin_panic
   7: std::panicking::begin_panic
   8: <T as core::any::Any>::type_id
   9: std::rt::lang_start_internal::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\rt.rs:49
  10: std::panicking::try::do_call<closure,i32>
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\panicking.rs:296
  11: panic_unwind::__rust_maybe_catch_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libpanic_unwind\lib.rs:82
  12: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\panicking.rs:275
  13: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\panic.rs:394
  14: std::rt::lang_start_internal
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\rt.rs:48
  15: main
  16: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  17: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  18: BaseThreadInitThunk
  19: RtlUserThreadStart
```

**Comment by alexcrichton** [comment]
Ah ok, thanks for the info! I don't believe this is related to symbolication of inline frames, but rather you're compiling without debuginfo and symbolication on MSVC critically relies on debug symbols being available. If you turn on `debug = 1` in `Cargo.toml` you should see the right symbols. Without a symbol though msvc just does its best and guesses the "nearest symbol" which is often wrong.
